name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 當推送到 main 分支時觸發此 workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 新增步驟：創建 config.js 文件並寫入 API Key
      - name: Create config.js with API Key
        run: |
          echo "const GEMINI_API_KEY = '${{ secrets.GEMINI_API_KEY }}';" > config.js
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # 確保環境變數在這裡可用

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # 您的網頁檔案所在的目錄，通常是根目錄
          # CNAME: your-custom-domain.com # 如果您有自訂網域，可以在此處設定
